### ISSUE TITLE
Can't include org.apache.anything in a mod

### ISSUE THREAD

**Issue by metadaddy** [MinecraftForge/FML#424]
I'm using Apache HttpComponents Client in [my mod](https://github.com/metadaddy-sfdc/Forcecraft). I wrote a script to create a 'fat jar' with the Apache class and all worked well in 1.6.4.

In 1.7.2, I figured out the Gradle magic to create a fat jar, but encountered an error:

```
[22:54:06 INFO]: Client> java.lang.NoClassDefFoundError: org/apache/http/client/ResponseHandler
[22:54:06 INFO]: Client>    at us.forcecraft.Forcecraft.aboutToStart(Forcecraft.java:138) ~[Forcecraft.class:?]
[22:54:06 INFO]: Client>    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.6.0_65]
...lots more stacktrace...
```

After much investigation, I found the cause: `FMLTweaker` adds `org.apache` as a class loader exclusion:

```
public void injectIntoClassLoader(LaunchClassLoader classLoader)
{
    classLoader.addClassLoaderExclusion("org.apache.");
    classLoader.addTransformerExclusion("cpw.mods.fml.repackage.");
    ...
```

It looks like this was done when log4j was added in 557357fe179529e0b44aab2f3fcef0c5adf981d5. Could you narrow the exclusion to something like `org.apache.logging.log4j` and `org.apache.commons.lang3` to allow mods to use other Apache classes?
